diging/conceptpower

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/web/UserEditController.java
Fetch Email id and pre-populate it.
> Added changes to pre-fill emailid in Edit User Page

- Conceptpower+Spring/src/main/webapp/resources/css/style.css
[CCP-75] Change made to css file to include pointer during hover
> Incuded hover style

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/home.jsp
- Conceptpower+Spring/src/main/webapp/resources/txt-layout/css/base.css
[CCP-88] Made UI changes for detail dialog box
> Changes for aligning details in center

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/sidebar.jsp
Fixed 404 error while user login after searching for a word from homescreen
> Fixed issue from CCP-94

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptSearch.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/SearchFieldNames.java
[CCP-74] Tested the flow using this URL and was able to fetch the results successfully. http://localhost:8080/conceptpower/rest/ConceptSearch?type_uri=http://www.digitalhps.org/types/TYPE_6e11d4cd-3be1-4d6f-8eeb-c8673d68fd90&operator=and
> Changes for type uri

- Conceptpower+Spring/pom.xml
- Conceptpower+Spring/src/main/webapp/WEB-INF/tiles/skeleton.jsp
[CCP-122] Removed the default value from pom and made changes in skeleton to make the condition work as expected.
> Changes for displaying pullrequest values

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/web/AddUserController.java
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/user/add.jsp
Included Check box to make a user as admin while adding the user
> Made code changes for CCP-90

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptListConceptsView.jsp
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptWrapperAddView.jsp
[CCP-80] Aligned details dialog in middle of screen
> Changes for other details dialog

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/validation/ConceptListAddValidator.java
[CCP-123] Included a condition for checking if the description is changed.
> Included old name for checking if the description alone has been changed

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/TypeEditView.jsp
[CCP-115] Changes onkeypress to onkeyup for triggering the function on pressing backspace.
> Changes for enabliing edit button on press of backspace.

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptEditView.jsp
[CCP-116] Fixed duplicate synonym issue in concept edit screen.
> Changes for preventing duplicate synonyms

- Conceptpower+Spring/pom.xml
Added Cobertura for conceptpower
> Added cobertura for CCP

- Conceptpower+Spring/pom.xml
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/xml/XMLConceptMessage.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/xml/XMLTypeMessage.java
> [CCP-139] updated Apache commons-lang to 3.4 and used new escape method

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/LoginController.java
[CCP-140] Fixed error message display when login fails
> Changes for displaying error message while login fails

- Conceptpower+Spring/.classpath
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptIDLookup.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptLookup.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptSearch.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/Concepts.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/SynonymSearch.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/TypeIdLookup.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/web/ConceptListController.java
- Conceptpower+Spring/src/main/webapp/WEB-INF/tiles/skeleton.jsp
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptListConceptsView.jsp
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/home.jsp
- Conceptpower+Spring/src/main/webapp/WEB-INF/web.xml
> [CCP-158] added encoding filter; added response header for API methods;

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/impl/ConceptManager.java
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/home.jsp
> [CCP-128] when adding concept, id is first added before concept is

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/lucene/luceneindex.jsp
Changes for reloading last run timestamp when index concepts and delete concepts button is triggered.
> [CCP-162] Reloads last run timestamp

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/core/ConceptEntry.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/root/DatabaseClient.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/root/DatabaseManager.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/ChangeEvent.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/ChangeEventConstants.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/IConceptManager.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/IIndexService.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/impl/ConceptManager.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/core/impl/IndexService.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/rest/Concepts.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/ConceptAddController.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/ConceptDeleteController.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/ConceptEditController.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/ConceptListEditController.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/web/ConceptWrapperAddController.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/wrapper/ConceptEntryWrapper.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/xml/XMLConceptMessage.java
- Conceptpower+Spring/src/test/java/edu/asu/conceptpower/core/ConceptManagerTest.java
- Conceptpower+Spring/src/test/java/edu/asu/conceptpower/wrapper/impl/ConceptEntryWrapperCreatorTest.java
All the changes from CCP-136 is moved to the new branch
CCP-136 new branch. All the changes are moved due to
rebasing and merge issues. Once CCP-136 new branch is merged
to develop. Both CCP-136 and CCP-136-New-Branch can be removed.
> [CCP-136] Initial commit from CCP-136 old branch

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/rest/Concepts.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/servlet/rest/JsonFields.java
URI will be displayed in the output json when
concept is added through Rest calls
> [CCP-157] Changes for including uri in add concept

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptWrapperAddView.jsp
Details from ajax call is parsed and displayed on the
modal.
> [CCP-164] Details are parsed now to be displayed

- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptAddView.jsp
Following changes are made to concept add screen.
1) When user does not enter any value for Term field
and tries to click on search, we do not hit the database,
instead we display error message.
2) In case of any error during ajax call we display
processing error to the user.
3) When user tries to search a word that is not in VIAF an
unknown alert box was appearing on the screen. Now handled
that condition by clearing the data table and displaying proper error
message.
4) Changed the button size to small to make it look better.
> [CCP-168] Form will not be submitted when enter is pressed

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptIDLookup.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptLookup.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/SynonymSearch.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/IConceptMessage.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/json/AlternativeId.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/json/ConceptEntryMessage.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/json/ConceptTypeMessage.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/json/JsonConceptMessage.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/msg/xml/XMLConceptMessage.java
- Conceptpower+Spring/src/test/java/edu/asu/conceptpower/servlet/rest/ConceptIDLookupTest.java
Previously pagination was added after root element. Just updated
the root element.
> [CCP-176] Root element is added correctly.

- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/core/IConceptTypeManger.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/core/impl/ConceptTypesManager.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/db/TypeDatabaseClient.java
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/web/ConceptTypesController.java
- Conceptpower+Spring/src/main/webapp/WEB-INF/views/auth/concepts/ConceptTypesView.jsp
Server side pagination is introduced in concept types screen. Pagination will be introduced for concept search screen in next PR.
> [CCP-177] Introduced pagination in concept types screen

- Conceptpower+Spring/src/integration-test/java/edu/asu/conceptpower/rest/ConceptSearchIT.java
- Conceptpower+Spring/src/integration-test/resources/output/conceptSearchNoSearchParameters.json
- Conceptpower+Spring/src/integration-test/resources/output/conceptSearchNoSearchParameters.xml
- Conceptpower+Spring/src/main/java/edu/asu/conceptpower/rest/ConceptSearchParameterValidator.java
From now on concept search rest api requires atleast one search parameter. If no
parameter is provided, the system returns the error message "No search condition
present" and return 400 http status code.
Previously the system went into 500 error when no parameter is provided.
> [CCP-210] Concept search requires atleast one search parameter
